name: Feature request
description: File a new feature request
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: reason
    attributes:
      label: Reason for feature
      description: Describe the reason or motivation behind the feature request
      placeholder: e.g. "I cannot accomplish ... because ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe your proposed solution / idea of the feature.
      placeholder: e.g. "Add a new button that ..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives / Available workarounds
      description: A clear and concise description of any alternative solutions or workarounds you've considered.
      placeholder: e.g. "I can currently work around this by ..." or "No alternatives found."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Anything else that is important to know?
    validations:
      required: false
